.TH NOTEDRILLER "1" "JUNE 2025" "NOTEDRILLER" "User Commands"
.SH NAME
notedriller \- drill yourself on guitar notes and CAGED chords
.SH SYNOPSIS
.B notedriller [--bpm 120.0] [--chord | --single-string] [--no-color]

.SH DESCRIPTION
.\" Add any additional description here
.PP
Drill yourself on guitar notes to help memorize the positions of notes on the fretboard,
or on CAGED chords to help you memorize the basic chord names and shapes all over the
fretboard.  Only six-string standard tuning is supported.
.SH OPTIONS
.TP
\fB\-b, --bpm\fR
Set the drilling rate to the specified BPM (beats per minute).  Higher values are
faster, the default is 40 BPM, which is quite slow.
.TP
\fB\-c, --chord\fR
Drills you on CAGED chords, rather than on notes, which is the default.
.TP
\fB\-C, --no-color\fR
Ordinarily the output of notedriller is colorized with ASCII escape codes.
This option suppresses that behavior.
.TP
\fB\-s, --single-string\fR
Drill notes on a single string at a time instead of on all six strings at once.
.SH EXAMPLES
.PP
Note drilling mode:
.nf

$ notedriller
Note drilling mode.
bpm = 40.000000
E ............



 |-------|------|------|------|------|------|------|-----|-----|-----|-----|#####|-----|----|----|----|----|----|----|---|---|---|---|###|
 |-------|------|------|------|######|------|------|-----|-----|-----|-----|-----|-----|----|----|----|####|----|----|---|---|---|---|---|
 |-------|------|------|------|------|------|------|-----|#####|-----|-----|-----|-----|----|----|----|----|----|----|---|###|---|---|---|
 |-------|######|------|------|------|------|------|-----|-----|-----|-----|-----|-----|####|----|----|----|----|----|---|---|---|---|---|
 |-------|------|------|------|------|------|######|-----|-----|-----|-----|-----|-----|----|----|----|----|----|####|---|---|---|---|---|
 |-------|------|------|------|------|------|------|-----|-----|-----|-----|#####|-----|----|----|----|----|----|----|---|---|---|---|###|
 0       1      2      3      4      5      6      7     8     9    10    11    12    13   14   15   16   17   18   19  20  21  22  23  24



Db.........
.fi
.PP
Single string note drilling mode:
.nf

$ notedriller -s
Note drilling mode.
bpm = 40.000000
B  on the E string............
 |-------|------|------|------|------|------|######|-----|-----|-----|-----|-----|-----|----|----|----|----|----|####|---|---|---|---|---|
 0       1      2      3      4      5      6      7     8     9    10    11    12    13   14   15   16   17   18   19  20  21  22  23  24
C  on the D string............
 |-------|------|------|------|------|------|------|-----|-----|#####|-----|-----|-----|----|----|----|----|----|----|---|---|###|---|---|
 0       1      2      3      4      5      6      7     8     9    10    11    12    13   14   15   16   17   18   19  20  21  22  23  24
G  on the G string............
 |-------|------|------|------|------|------|------|-----|-----|-----|-----|#####|-----|----|----|----|----|----|----|---|---|---|---|###|
 0       1      2      3      4      5      6      7     8     9    10    11    12    13   14   15   16   17   18   19  20  21  22  23  24
A# on the B string............
 |-------|------|------|------|------|------|------|-----|-----|-----|#####|-----|-----|----|----|----|----|----|----|---|---|---|###|---|
 0       1      2      3      4      5      6      7     8     9    10    11    12    13   14   15   16   17   18   19  20  21  22  23  24
.fi
.PP
CAGED chord drilling mode:
.nf

$ notedriller -c
hord drilling mode.
bpm = 40.000000
A-minor-shaped Gb minor............



 |-------|------|------|------|------|------|------|-----|#####|-----|-----|-----|-----|----|----|----|----|----|----|---|###|---|---|---|
 |-------|------|------|------|------|------|------|-----|-----|#####|-----|-----|-----|----|----|----|----|----|----|---|---|###|---|---|
 |-------|------|------|------|------|------|------|-----|-----|-----|#####|-----|-----|----|----|----|----|----|----|---|---|---|###|---|
 |-------|------|------|------|------|------|------|-----|-----|-----|#####|-----|-----|----|----|----|----|----|----|---|---|---|###|---|
 |-------|------|------|------|------|------|------|-----|#####|-----|-----|-----|-----|----|----|----|----|----|----|---|###|---|---|---|
 |-------|------|------|------|------|------|------|-----|#####|-----|-----|-----|-----|----|----|----|----|----|----|---|###|---|---|---|
 0       1      2      3      4      5      6      7     8     9    10    11    12    13   14   15   16   17   18   19  20  21  22  23  24
Root  Third  Minor Third  Fifth



A-minor-shaped F# minor............



 |-------|------|------|------|------|------|------|-----|#####|-----|-----|-----|-----|----|----|----|----|----|----|---|###|---|---|---|
 |-------|------|------|------|------|------|------|-----|-----|#####|-----|-----|-----|----|----|----|----|----|----|---|---|###|---|---|
 |-------|------|------|------|------|------|------|-----|-----|-----|#####|-----|-----|----|----|----|----|----|----|---|---|---|###|---|
 |-------|------|------|------|------|------|------|-----|-----|-----|#####|-----|-----|----|----|----|----|----|----|---|---|---|###|---|
 |-------|------|------|------|------|------|------|-----|#####|-----|-----|-----|-----|----|----|----|----|----|----|---|###|---|---|---|
 |-------|------|------|------|------|------|------|-----|#####|-----|-----|-----|-----|----|----|----|----|----|----|---|###|---|---|---|
 0       1      2      3      4      5      6      7     8     9    10    11    12    13   14   15   16   17   18   19  20  21  22  23  24
Root  Third  Minor Third  Fifth
.SH AUTHOR
Written by Stephen M. Cameron
.br
